// Code generated by "stringer -type LogLevel -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Debug-1]
	_ = x[Info-2]
	_ = x[Warn-3]
	_ = x[Error-4]
}

const _LogLevel_name = "DEBUGINFOWARNERROR"

var _LogLevel_index = [...]uint8{0, 5, 9, 13, 18}

func (i LogLevel) String() string {
	i -= 1
	if i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
